# Script Assignment 4

**Your name:** Katelyn Choudhari             

**Your ID:** 5368756

Load macrodata csv file then perform following operations.

All solutions should be only in Jupyter Notebook.
Provide comments for every solution.
Code in Code cell and Text in Markdown cell.Markdown cell.

In [155]:
import pandas as pd
import numpy as np

#load the data into a dataframe
macroDF = pd.read_csv('macrodata.csv')

print(macroDF)

     year  quarter    realgdp  realcons   realinv  realgovt  realdpi      cpi  \
0    1959        1   2710.349    1707.4   286.898   470.045   1886.9   28.980
1    1959        2   2778.801    1733.7   310.859   481.301   1919.7   29.150
2    1959        3   2775.488    1751.8   289.226   491.260   1916.4   29.350
3    1959        4   2785.204    1753.7   299.356   484.052   1931.3   29.370
4    1960        1   2847.699    1770.5   331.722   462.199   1955.5   29.540
..    ...      ...        ...       ...       ...       ...      ...      ...
198  2008        3  13324.600    9267.7  1990.693   991.551   9838.3  216.889
199  2008        4  13141.920    9195.3  1857.661  1007.273   9920.4  212.174
200  2009        1  12925.410    9209.2  1558.494   996.287   9926.4  212.671
201  2009        2  12901.504    9189.0  1456.678  1023.528  10077.5  214.469
202  2009        3  12990.341    9256.0  1486.398  1044.088  10040.6  216.385

         m1  tbilrate  unemp      pop  infl  realint
0     139.7      2.82    5.8  177.146  0.00     0.00
1     141.7      3.08    5.1  177.830  2.34     0.74
2     140.5      3.82    5.3  178.657  2.74     1.09
3     140.0      4.33    5.6  179.386  0.27     4.06
4     139.6      3.50    5.2  180.007  2.31     1.19
..      ...       ...    ...      ...   ...      ...
198  1474.7      1.17    6.0  305.270 -3.16     4.33
199  1576.5      0.12    6.9  305.952 -8.79     8.91
200  1592.8      0.22    8.1  306.547  0.94    -0.71
201  1653.6      0.18    9.2  307.226  3.37    -3.19
202  1673.9      0.12    9.6  308.013  3.56    -3.44

[203 rows x 14 columns]

Use unstack on years 1959-1999 and then stack for the remaining years in the years column. - 2 points

In [158]:
#split the years into two categories 1959-1999 and 1999 and after and apply unstack/stack
unstackData = macroDF[(macroDF['year'] >= 1959) & (macroDF['year'] <= 1999)].set_index(['year', 'quarter']).unstack()
stackData = macroDF[macroDF['year'] > 1999].set_index(['year', 'quarter']).stack()

print('\n Unstacked Years: \n', unstackData)
print('\n Stacked Years: \n', stackData)

 Unstacked Years:
            realgdp                                  realcons                  \
quarter          1          2          3          4        1       2       3
year
1959      2710.349   2778.801   2775.488   2785.204   1707.4  1733.7  1751.8
1960      2847.699   2834.390   2839.022   2802.616   1770.5  1792.9  1785.8
1961      2819.264   2872.005   2918.419   2977.830   1787.7  1814.3  1823.1
1962      3031.241   3064.709   3093.047   3100.563   1879.4  1902.5  1917.9
1963      3141.087   3180.447   3240.332   3264.967   1958.2  1976.9  2003.8
1964      3338.246   3376.587   3422.469   3431.957   2060.5  2096.7  2135.2
1965      3516.251   3563.960   3636.285   3724.014   2188.8  2213.0  2251.0
1966      3815.423   3828.124   3853.301   3884.520   2348.5  2354.5  2381.5
1967      3918.740   3919.556   3950.826   3980.970   2405.3  2438.1  2450.6
1968      4063.013   4131.998   4160.267   4178.293   2524.6  2563.3  2611.5
1969      4244.100   4256.460   4283.378   4263.261   2652.9  2669.8  2682.7
1970      4256.573   4264.289   4302.259   4256.637   2720.7  2733.2  2757.1
1971      4374.016   4398.829   4433.943   4446.264   2802.2  2827.9  2850.4
1972      4525.769   4633.101   4677.503   4754.546   2936.5  2992.6  3038.8
1973      4876.166   4932.571   4906.252   4953.050   3167.0  3165.4  3176.7
1974      4909.617   4922.188   4873.520   4854.340   3139.7  3150.6  3163.6
1975      4795.295   4831.942   4913.328   4977.511   3143.4  3195.8  3241.4
1976      5090.663   5128.947   5154.072   5191.499   3341.2  3371.8  3407.5
1977      5251.762   5356.131   5451.921   5450.793   3491.3  3510.6  3544.1
1978      5469.405   5684.569   5740.300   5816.222   3618.5  3695.9  3711.4
1979      5825.949   5831.418   5873.335   5889.495   3760.2  3758.0  3794.9
1980      5908.467   5787.373   5776.617   5883.460   3798.4  3712.2  3752.0
1981      6005.717   5957.795   6030.184   5955.062   3822.8  3822.8  3838.3
1982      5857.333   5889.074   5866.370   5871.001   3833.9  3847.7  3877.2
1983      5944.020   6077.619   6197.468   6325.574   3986.6  4065.7  4137.6
1984      6448.264   6559.594   6623.343   6677.264   4239.2  4299.9  4333.0
1985      6740.275   6797.344   6903.523   6955.918   4464.6  4505.2  4590.8
1986      7022.757   7050.969   7118.950   7153.359   4639.3  4688.7  4770.7
1987      7193.019   7269.510   7332.558   7458.022   4792.1  4856.3  4910.4
1988      7496.600   7592.881   7632.082   7733.991   5004.4  5040.8  5080.6
1989      7806.603   7865.016   7927.393   7944.697   5159.3  5182.4  5236.1
1990      8027.693   8059.598   8059.476   7988.864   5303.3  5320.8  5341.0
1991      7950.164   8003.822   8037.538   8069.046   5284.4  5324.7  5345.0
1992      8157.616   8244.294   8329.361   8417.016   5434.5  5466.7  5527.1
1993      8432.485   8486.435   8531.108   8643.769   5617.2  5671.1  5732.7
1994      8727.919   8847.303   8904.289   9003.180   5848.1  5891.5  5938.7
1995      9025.267   9044.668   9120.684   9184.275   6004.3  6053.5  6107.6
1996      9247.188   9407.052   9488.879   9592.458   6206.9  6277.1  6314.6
1997      9666.235   9809.551   9932.672  10008.874   6430.2  6456.2  6566.0
1998     10103.425  10194.277  10328.787  10507.575   6707.2  6822.6  6913.1
1999     10601.179  10684.049  10819.914  11014.254   7088.3  7199.9  7286.4

                  realinv            ...      pop            infl         \
quarter       4         1         2  ...        3        4      1      2
year                                 ...
1959     1753.7   286.898   310.859  ...  178.657  179.386   0.00   2.34
1960     1788.2   331.722   298.152  ...  181.528  182.287   2.31   0.14
1961     1859.6   266.405   286.246  ...  184.524  185.242  -0.40   1.47
1962     1945.1   334.271   331.039  ...  187.323  188.013   2.26   0.13
1963     2020.6   343.721   348.730  ...  190.028  190.668   0.53   2.75
1964     2141.2   379.523   377.778  ...  192.631  193.223   0.13   0.90
1965     2314.3   429.145   429.119  ...  194.997  195.539   1.28   2.54
1966     2391.4   484.244   475.408  ...  197.207  197.736   4.99   2.10
1967     2465.7   460.007   440.393  ...  199.311  199.808   2.42   3.61
1968     2623.5   472.907   492.026  ...  201.290  201.760   3.50   5.77
1969     2704.1   512.686   508.601  ...  203.302  203.849   6.67   5.47
1970     2749.6   476.925   478.419  ...  205.788  206.466   6.28   4.13
1971     2897.8   517.935   533.986  ...  208.345  208.917   2.00   4.96
1972     3110.1   561.147   595.495  ...  210.479  210.985   2.90   2.88
1973     3167.4   645.654   675.837  ...  212.475  212.932   9.26   4.55
1974     3117.3   631.230   628.102  ...  214.451  214.931  10.96   9.86
1975     3275.7   493.212   476.085  ...  216.587  217.095   5.32   7.48
1976     3451.8   585.541   610.513  ...  218.644  219.179   2.14   6.37
1977     3597.5   646.198   696.141  ...  220.904  221.477   8.76   5.30
1978     3741.3   727.504   777.454  ...  223.271  223.865   7.58   9.89
1979     3805.0   819.556   817.660  ...  225.801  226.451  12.08  13.37
1980     3802.0   781.114   710.640  ...  228.417  228.937  14.60   8.32
1981     3809.3   795.091   757.240  ...  230.641  231.157   8.62  10.63
1982     3947.9   692.514   691.900  ...  232.816  233.322   2.53  10.39
1983     4203.2   645.110   707.372  ...  234.907  235.385   3.66   4.03
1984     4390.1   921.763   952.841  ...  236.976  237.468   4.67   3.09
1985     4600.9   927.375   943.383  ...  239.113  239.638   4.89   2.61
1986     4799.4   967.442   945.972  ...  241.274  241.784  -4.39   2.93
1987     4922.2   945.776   947.100  ...  243.446  243.981   4.64   3.89
1988     5140.4   964.398   987.858  ...  245.693  246.224   4.12   4.41
1989     5261.7  1045.975  1033.753  ...  248.067  248.659   6.22   4.52
1990     5299.5  1021.070  1021.360  ...  251.057  251.889   4.37   4.93
1991     5342.6   896.210   891.704  ...  254.435  255.214   1.19   3.24
1992     5594.6   927.796   988.912  ...  257.861  258.679   3.17   3.14
1993     5783.7  1054.979  1063.263  ...  261.163  261.919   2.79   1.94
1994     5997.3  1166.845  1234.855  ...  264.301  265.044   2.45   3.25
1995     6150.6  1282.090  1247.610  ...  267.456  268.151   3.44   2.10
1996     6366.1  1287.128  1353.795  ...  270.581  271.360   3.60   2.30
1997     6641.1  1451.304  1543.976  ...  273.852  274.626   1.25   1.25
1998     7019.1  1672.732  1652.716  ...  277.003  277.790   0.49   2.46
1999     7389.2  1809.993  1803.674  ...  280.203  280.976   2.90   1.92

                      realint
quarter      3      4       1     2     3     4
year
1959      2.74   0.27    0.00  0.74  1.09  4.06
1960      2.70   1.21    1.19  2.55 -0.34  1.08
1961      0.80   0.80    2.77  0.81  1.52  1.80
1962      2.11   0.79    0.47  2.65  0.67  2.08
1963      0.78   2.46    2.38  0.29  2.60  1.06
1964      1.29   2.05    3.38  2.57  2.25  1.71
1965      0.89   2.90    2.65  1.30  3.04  1.46
1966      4.90   0.61   -0.37  2.55  0.33  4.39
1967      3.58   4.72    1.80  0.17  0.84  0.18
1968      4.56   4.51    1.67 -0.28  0.65  1.34
1969      5.40   6.38   -0.58  1.02  1.63  1.26
1970      5.11   5.04    0.47  2.52  1.04 -0.18
1971      2.94   2.92    1.65 -0.19  1.75  0.95
1972      3.81   4.71    0.64  0.98  0.66  0.38
1973     12.47  10.39   -3.28  2.64 -4.41 -2.71
1974     13.56  10.07   -3.16 -1.96 -5.40 -3.11
1975      6.61   6.50    0.22 -1.91 -0.34 -1.24
1976      6.27   5.49    2.77 -1.09 -1.22 -0.92
1977      5.23   7.08   -4.16 -0.24  0.59 -0.88
1978      9.65   8.26   -1.24 -3.18 -2.01  0.76
1979     11.88  14.62   -2.66 -4.07 -1.38 -2.68
1980     10.04  11.64   -0.85 -0.42  0.30  3.11
1981      8.22   4.26    5.32  4.69  6.36  7.07
1982      2.45  -0.82   10.42  1.58  5.65  8.77
1983      3.99   5.13    4.56  4.66  5.01  3.76
1984      3.82   2.28    4.76  6.85  6.37  5.87
1985      2.96   5.13    3.36  4.56  4.17  2.01
1986      2.55   4.33   10.95  3.13  2.76  1.10
1987      4.20   3.46    0.97  1.79  1.99  2.29
1988      4.70   4.31    1.64  2.07  2.52  3.72
1989      2.88   6.64    2.44  3.63  4.88  1.01
1990      8.79   3.88    3.44  2.76 -1.46  2.79
1991      2.93   3.19    4.65  2.29  2.25  0.95
1992      3.40   3.09    0.71  0.36 -0.44  0.02
1993      3.03   1.92    0.13  1.08 -0.04  1.13
1994      2.69   2.93    1.02  0.96  2.00  2.60
1995      2.35   3.11    2.28  3.42  2.97  2.05
1996      3.05   3.02    1.31  2.79  2.00  1.97
1997      2.73   1.24    3.85  3.76  2.29  3.88
1998      1.71   1.95    4.53  2.52  2.78  2.43
1999      3.35   2.85    1.49  2.62  1.41  2.35

[41 rows x 48 columns]

 Stacked Years:
 year  quarter
2000  1        realgdp     11043.044
               realcons     7501.300
               realinv      1887.836
               realgovt      685.216
               realdpi      8053.400
                             ...
2009  3        tbilrate        0.120
               unemp           9.600
               pop           308.013
               infl            3.560
               realint        -3.440
Length: 468, dtype: float64

Use Swaplevel on columns "cpi" and "realint" - 1 Point

In [161]:
#copy columns cpi and realint from dataframe
macroDF1 = macroDF[['cpi', 'realint']].copy()

#make a multiindex with two levels that groups columns under Factors
macroDF1.columns = pd.MultiIndex.from_tuples([('Factors', 'cpi'), ('Factors', 'realint')])

#swap the two levels by columns
swaplevel = macroDF1.swaplevel(axis = 1)

print('\n MultiIndex: \n', macroDF1)
print('\n Swaplevel: \n', swaplevel)

 MultiIndex:
      Factors
         cpi realint
0     28.980    0.00
1     29.150    0.74
2     29.350    1.09
3     29.370    4.06
4     29.540    1.19
..       ...     ...
198  216.889    4.33
199  212.174    8.91
200  212.671   -0.71
201  214.469   -3.19
202  216.385   -3.44

[203 rows x 2 columns]

 Swaplevel:
          cpi realint
     Factors Factors
0     28.980    0.00
1     29.150    0.74
2     29.350    1.09
3     29.370    4.06
4     29.540    1.19
..       ...     ...
198  216.889    4.33
199  212.174    8.91
200  212.671   -0.71
201  214.469   -3.19
202  216.385   -3.44

[203 rows x 2 columns]

Merge all columns that start with "real"  into new column "unreal". (Use RE from the previous notebook if needed) - 1 Point

In [164]:
#get all columns that start with real
real = macroDF.filter(regex = '^real').columns

#merge all real columns values into unreal column
macroDF['unreal'] = macroDF[real].sum(axis = 1)

print('\n Unreal column: \n', macroDF.unreal)
print('\n Unreal and Real columns: \n', macroDF[['unreal'] + list(real)])

 Unreal column:
 0       7061.592
1       7225.101
2       7225.264
3       7257.672
4       7368.810
         ...
198    35417.174
199    35131.464
200    34615.081
201    34645.020
202    34813.987
Name: unreal, Length: 203, dtype: float64

 Unreal and Real columns:
         unreal    realgdp  realcons   realinv  realgovt  realdpi  realint
0     7061.592   2710.349    1707.4   286.898   470.045   1886.9     0.00
1     7225.101   2778.801    1733.7   310.859   481.301   1919.7     0.74
2     7225.264   2775.488    1751.8   289.226   491.260   1916.4     1.09
3     7257.672   2785.204    1753.7   299.356   484.052   1931.3     4.06
4     7368.810   2847.699    1770.5   331.722   462.199   1955.5     1.19
..         ...        ...       ...       ...       ...      ...      ...
198  35417.174  13324.600    9267.7  1990.693   991.551   9838.3     4.33
199  35131.464  13141.920    9195.3  1857.661  1007.273   9920.4     8.91
200  34615.081  12925.410    9209.2  1558.494   996.287   9926.4    -0.71
201  34645.020  12901.504    9189.0  1456.678  1023.528  10077.5    -3.19
202  34813.987  12990.341    9256.0  1486.398  1044.088  10040.6    -3.44

[203 rows x 7 columns]

Provide an example for join() - 1 Point

In [181]:
#split the dataframe to demonstrate how to use join
macroDF2 = macroDF[['year', 'quarter', 'realgdp', 'realcons']].set_index(['year', 'quarter'])
macroDF3 = macroDF[['year', 'quarter', 'cpi', 'realint']].set_index(['year', 'quarter'])

print('\n Split dataframe: \n', macroDF2)
print('\n Split dataframe: \n', macroDF3)

#join via year and quarter fields
macroJoin = macroDF2.join(macroDF3)
print('\n Joined dataframe: \n', macroJoin)

 Split dataframe:
                 realgdp  realcons
year quarter
1959 1         2710.349    1707.4
     2         2778.801    1733.7
     3         2775.488    1751.8
     4         2785.204    1753.7
1960 1         2847.699    1770.5
...                 ...       ...
2008 3        13324.600    9267.7
     4        13141.920    9195.3
2009 1        12925.410    9209.2
     2        12901.504    9189.0
     3        12990.341    9256.0

[203 rows x 2 columns]

 Split dataframe:
                   cpi  realint
year quarter
1959 1         28.980     0.00
     2         29.150     0.74
     3         29.350     1.09
     4         29.370     4.06
1960 1         29.540     1.19
...               ...      ...
2008 3        216.889     4.33
     4        212.174     8.91
2009 1        212.671    -0.71
     2        214.469    -3.19
     3        216.385    -3.44

[203 rows x 2 columns]

 Joined dataframe:
                 realgdp  realcons      cpi  realint
year quarter
1959 1         2710.349    1707.4   28.980     0.00
     2         2778.801    1733.7   29.150     0.74
     3         2775.488    1751.8   29.350     1.09
     4         2785.204    1753.7   29.370     4.06
1960 1         2847.699    1770.5   29.540     1.19
...                 ...       ...      ...      ...
2008 3        13324.600    9267.7  216.889     4.33
     4        13141.920    9195.3  212.174     8.91
2009 1        12925.410    9209.2  212.671    -0.71
     2        12901.504    9189.0  214.469    -3.19
     3        12990.341    9256.0  216.385    -3.44

[203 rows x 4 columns]

Provide an example for concat() with index enabled - 1 Point

In [170]:
#split the dataframe to demonstrate how to use concat
macroDF4 = macroDF[['year', 'quarter', 'realgdp']]
macroDF5 = macroDF[['year', 'quarter', 'realcons']]

print('\n Split dataframe: \n', macroDF4)
print('\n Split dataframe: \n', macroDF5)

#concat via columns
macroConcat = pd.concat([macroDF4, macroDF5], axis = 1)
print('\n Concatenated dataframe: \n', macroConcat)

 Split dataframe:
      year  quarter    realgdp
0    1959        1   2710.349
1    1959        2   2778.801
2    1959        3   2775.488
3    1959        4   2785.204
4    1960        1   2847.699
..    ...      ...        ...
198  2008        3  13324.600
199  2008        4  13141.920
200  2009        1  12925.410
201  2009        2  12901.504
202  2009        3  12990.341

[203 rows x 3 columns]

 Split dataframe:
      year  quarter  realcons
0    1959        1    1707.4
1    1959        2    1733.7
2    1959        3    1751.8
3    1959        4    1753.7
4    1960        1    1770.5
..    ...      ...       ...
198  2008        3    9267.7
199  2008        4    9195.3
200  2009        1    9209.2
201  2009        2    9189.0
202  2009        3    9256.0

[203 rows x 3 columns]

 Concatenated dataframe:
      year  quarter    realgdp  year  quarter  realcons
0    1959        1   2710.349  1959        1    1707.4
1    1959        2   2778.801  1959        2    1733.7
2    1959        3   2775.488  1959        3    1751.8
3    1959        4   2785.204  1959        4    1753.7
4    1960        1   2847.699  1960        1    1770.5
..    ...      ...        ...   ...      ...       ...
198  2008        3  13324.600  2008        3    9267.7
199  2008        4  13141.920  2008        4    9195.3
200  2009        1  12925.410  2009        1    9209.2
201  2009        2  12901.504  2009        2    9189.0
202  2009        3  12990.341  2009        3    9256.0

[203 rows x 6 columns]

Provide an example for concat() with index disabled - 1 Point

In [173]:
#split the dataframe to demonstrate how to use concat
macroDF4 = macroDF[['year', 'quarter', 'realgdp']]
macroDF5 = macroDF[['year', 'quarter', 'realcons']]

#concat via columns (axis = 1), with index disabled
macroConcatNoIndex = pd.concat([macroDF4, macroDF5], axis = 1, ignore_index = True)

print('Concatenated, index disabled, dataframe:\n', macroConcatNoIndex)

Concatenated, index disabled, dataframe:
         0  1          2     3  4       5
0    1959  1   2710.349  1959  1  1707.4
1    1959  2   2778.801  1959  2  1733.7
2    1959  3   2775.488  1959  3  1751.8
3    1959  4   2785.204  1959  4  1753.7
4    1960  1   2847.699  1960  1  1770.5
..    ... ..        ...   ... ..     ...
198  2008  3  13324.600  2008  3  9267.7
199  2008  4  13141.920  2008  4  9195.3
200  2009  1  12925.410  2009  1  9209.2
201  2009  2  12901.504  2009  2  9189.0
202  2009  3  12990.341  2009  3  9256.0

[203 rows x 6 columns]

Create a pivot table - 1 Point

In [176]:
#make pt that finds the average realinv per year
macroPT = macroDF.pivot_table(index = 'year', values = 'realinv', aggfunc = 'mean')

print('\n Pivot table - Average realinv per year: \n', macroPT)

 Pivot table - Average realinv per year:
           realinv
year
1959   296.584750
1960   296.503250
1961   294.585250
1962   331.980500
1963   354.271750
1964   383.491250
1965   437.300250
1966   475.826500
1967   454.066750
1968   480.496000
1969   508.495250
1970   475.086000
1971   529.254000
1972   591.929000
1973   661.289000
1974   612.577500
1975   504.073750
1976   605.899500
1977   697.443250
1978   781.524750
1979   806.443750
1980   717.862750
1981   782.406500
1982   672.792250
1983   735.461500
1984   952.146500
1985   943.287750
1986   936.866250
1987   965.727750
1988   988.457750
1989  1028.112750
1990   993.499250
1991   912.677250
1992   986.650250
1993  1074.834750
1994  1220.886250
1995  1258.923250
1996  1370.293750
1997  1540.807250
1998  1695.065500
1999  1844.295750
2000  1970.291500
2001  1831.901000
2002  1806.964000
2003  1871.626250
2004  2058.244500
2005  2172.227250
2006  2230.392500
2007  2146.185000
2008  1989.439500
2009  1500.523333

Provide an example for melt() - 1 Point

In [179]:
#melt dataframe, make fixed fields (year and quarter) and unpivot realgdp and realcons
macroMelt = macroDF.melt(id_vars = ['year', 'quarter'], value_vars = ['realgdp', 'realcons'], var_name = 'Factors', value_name = 'Value')

print('\n Melt: \n', macroMelt)

 Melt:
      year  quarter   Factors     Value
0    1959        1   realgdp  2710.349
1    1959        2   realgdp  2778.801
2    1959        3   realgdp  2775.488
3    1959        4   realgdp  2785.204
4    1960        1   realgdp  2847.699
..    ...      ...       ...       ...
401  2008        3  realcons  9267.700
402  2008        4  realcons  9195.300
403  2009        1  realcons  9209.200
404  2009        2  realcons  9189.000
405  2009        3  realcons  9256.000

[406 rows x 4 columns]